### ISSUE TITLE
Require Backing Type

### ISSUE THREAD

**Issue by davethenipper** [YashdalfTheGray/flintandsteel#68]
Require a "Type of Backing" from the list of backing types before allowing a submission.

**Comment by Mctalian** [comment]
How is this different than the "Type of Backing" field? (Keep in mind it's not working right now due to 3rd party issues)

**Comment by davethenipper** [comment]
ohhhhhh, okay cool.  Then we can delete this.

**Comment by davethenipper** [comment]
I guess the only thing here is to force them to choose a backing type once that is implemented.

**Comment by Mctalian** [comment]
Yeah, I think there is a "md-required" field for autocomplete that may or may not be working right now. You can change the title and description to call out requiring a "Type of Backing" from the list of backing types.

**Comment by davethenipper** [comment]
Updated ^^

**Comment by Mctalian** [comment]
#33 Is a bit of a blocker to moving forward with this.

**Comment by Mctalian** [comment]
Instead of relying on md-autocomplete and requiring the user to type in their backing type, we can open up a modal window that has checkboxes for each of the backing types. This way we don't need to rely on the 3rd party issues being fixed. I would almost reverse the order of the inputs at that point. Have the user click to back the idea, it opens the checkboxes, once they are selected the user can type any additional info in a text field.

**Comment by davethenipper** [comment]
That sounds good to me.  That way they don't type an entire wall of text and realize that a "type" exists for the role they were describing.

**Comment by YashdalfTheGray** [comment]
So I'm guessing that there hasn't been any updates on the md-chips/md-autocomplete front?

**Comment by Mctalian** [comment]
No and judging by their milestones it's not slated until mid to late July
but I don't know if we should bank on that or rethink our method a bit. I
think check boxes in a modal kind of make sense if we want them to choose a
provided backing type anyway... we can still use chips, but it would take
out autocorrect. Unless they are dependent on each other.

**Comment by YashdalfTheGray** [comment]
I don't think they are dependent on each other, I think that most things in the ng-material library are self-contained but to improve on your idea, we could just take away the text field and leave a button called something like "Back this project!" (quite like Kickstarter) and then show that modal. 

This solves a couple of different issues that we've been having with the backing field and we can also split the back process from the comment process. 

I also think that it makes our idea service a little less code (or maybe the ideaView controller) because we pull all that md-chip shit out. 

I could work on this while we wait on a backend decision.

**Comment by Mctalian** [comment]
Makes sense to me. The only use I see for the text box is specifying how
much money or time you can offer, which isn't super pertinent at that time.
Also the "how can I help?" Should at least be kept in mind. Though all of
those things can be handled during/just prior to building your team.

For example email to Mr. Monopoly Guy:
Yo how much money can you throw at me?

Email to Mr. Free Time Fred:
How much time can you spare, breh?

Email to Ms. Helpful Helen:
What do you have to offer? We need someone to run coffee, is that something
you'd like to do?

Etc.

**Comment by YashdalfTheGray** [comment]
Wait, what is this email thing? I know that there is a chip or an option that should say "How can I help?" but what's with the email?

I'm not trying to be confrontational, I think I missed something.

**Comment by Mctalian** [comment]
Just saying if an idea creator needed more information from a backer that
may or may not have been provided in the backer text field, they can send
them an email or contact them otherwise requesting or providing extra info.

The email is outside of RokStarter. Just providing cases where the backing
text might be useful and scenarios that could essentially fill that gap
anyway.

**Comment by YashdalfTheGray** [comment]
Oooohh, okay. I don't know why I didn't make that connection, sorry. Yeah, that makes sense.

**Comment by davethenipper** [comment]
A decision should be made on this. Do we want to force someone to choose a type of back?  Or do we want to back an idea in general?

**Comment by YashdalfTheGray** [comment]
Did we decide on anything for this? I'm leaning towards forcing someone to categorize their back.

**Comment by Mctalian** [comment]
I also think we should force.

**Comment by davethenipper** [comment]
User story added

**Comment by YashdalfTheGray** [comment]
Can we close this then?

**Comment by davethenipper** [comment]
Fine by me
