### ISSUE TITLE
Restructure DB

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#76]
After our conversation with the MKE guys today, I realized that our current DB structure is going to hurt us in the future. I took a picture of something Matt, David, and I drew/discussed in the recap meeting. I will figure out how to upload that later so we can discuss it. 7 days until my desktop is in my new house. Until then. Sad face.

**Comment by YashdalfTheGray** [comment]
So I've been thinking about this for a while and also thinking about changing the "schema" that we have. Couple of things that I've considered:

* Users, ideas, comments, backs, everything else that we can think of will have a uniqueid
* Comments and backs should live under an idea, otherwise they just live in a pool of comments and backs and that doesn't make logical sense. 
* Since using a document-based database lets us put whatever we want wherever we want it, we're going to have to control these things through the javascript code. There are patterns that we can and should follow for database access that are known to work well, for example the [visitor pattern](http://manski.net/2013/05/the-visitor-pattern-explained/) or the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern). 
* This also means that we're going to have to bring in prototypical inheritance in the mix here, it's not hard, just something else that we have to be careful about. Everything that goes into the database "inherits" from DbObject which has backing methods to store and recall so that that work doesn't have to be done over and over again. 

There are some other points that I'm probably forgetting here but as conversation continues, I'll probably remember then.

**Comment by Mctalian** [comment]
I wish you were still in Cleveland because this is going to be one of those things that are very difficult to discuss virtually.

**Comment by YashdalfTheGray** [comment]
Yeah, I know! Next week, I can put together a google hangout so we can work on it, or this week but I'm in training all week and my leave work times are highly variable.

**Comment by Mctalian** [comment]
Next week would be better for me as well. Still readjusting due to the post-vacation struggles.

**Comment by YashdalfTheGray** [comment]
I think we're going to need to add mongodb server and the mongodb node driver as dependencies to the project. Once that's done, we need to either 1) write some scripts to import test data or 2) have the mongodb server live somewhere so that everyone can access it. Either way, pulling out the data backend shouldn't be too difficult, it's going to require some legit coordination though. I'm thinking next week, you and I can start looking into it. I'll pull mongo into my branch for the project and make sure I can bring it up okay. 

What do you think?

**Comment by Mctalian** [comment]
Yash is working on this. Should get closed soon.

**Comment by YashdalfTheGray** [comment]
PR #110 live now.

**Comment by Mctalian** [comment]
PR #110 was merged in the past. Closing. We have a clean up task that should cover any residual tech debt. Though that might be winding down as well.
